sudo: required

language: generic

services:
  - docker

env:
  - IMAGE_FROM='jaschweder\/php:laravel' IMAGE_TO=jaschweder/php:laravel-ffmpeg DOWNSTREAM=false
  - IMAGE_FROM='jaschweder\/php:5.6-laravel' IMAGE_TO=jaschweder/php:5.6-laravel-ffmpeg DOWNSTREAM=false

script:
  - sed -e s/{IMAGE_FROM}/$IMAGE_FROM/g Dockerfile-template > Dockerfile
  - docker build -t $IMAGE_TO .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE_TO;
