sudo: required

services:
  - docker

script:
  - docker build -t jaschweder/php:sqlsrv .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jaschweder/php:sqlsrv;
  - chmod a+x ./script/after-success-build.sh
  - ./script/after-success-build.sh;
