sudo: required

language: ruby

services:
  - docker

env:
  - IMAGE_FROM='jaschweder\/php:tools' IMAGE_TO=jaschweder/php:server DOWNSTREAM=true
  - IMAGE_FROM='jaschweder\/php:7.0-tools' IMAGE_TO=jaschweder/php:7.0-server DOWNSTREAM=true
  - IMAGE_FROM='jaschweder\/php:7.1-tools' IMAGE_TO=jaschweder/php:7.1-server DOWNSTREAM=true
  - IMAGE_FROM='jaschweder\/php:7.2-tools' IMAGE_TO=jaschweder/php:7.2-server DOWNSTREAM=true
  - IMAGE_FROM='jaschweder\/php:sqlsrv-tools' IMAGE_TO=jaschweder/php:sqlsrv-server DOWNSTREAM=true
  - IMAGE_FROM='jaschweder\/php:5.6-tools' IMAGE_TO=jaschweder/php:5.6-server DOWNSTREAM=false
  - IMAGE_FROM='jaschweder\/php:5.6-sybase-tools' IMAGE_TO=jaschweder/php:5.6-sybase-server DOWNSTREAM=false

script:
  - export pattern=s/{IMAGE_FROM}/$IMAGE_FROM/g
  - sed $pattern Dockerfile-template > Dockerfile
  - docker build -t $IMAGE_TO .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE_TO;
  - chmod a+x ./script/after-success-build.sh
  - ./script/after-success-build.sh;
