sudo: required

language: php

services:
  - docker

env:
  - IMAGE_FROM='jaschweder\/php' IMAGE_TO=jaschweder/php:tools
  - IMAGE_FROM='jaschweder\/php:5.6' IMAGE_TO=jaschweder/php:5.6-tools

script:
  - export pattern=s/{IMAGE_FROM}/$IMAGE_FROM/g
  - sed $pattern Dockerfile-template > Dockerfile
  - docker build -t $IMAGE_TO .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE_TO;
  - chmod a+x ./script/after-success-build.sh
  - ./script/after-success-build.sh;
