sudo: required

language: generic

services:
  - docker

env:
  - IMAGE_FROM='jaschweder\/php:tools' IMAGE_TO=jaschweder/php:metrics

script:
  - sed -e s/{IMAGE_FROM}/$IMAGE_FROM/g Dockerfile-template > Dockerfile
  - docker build -t $IMAGE_TO .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE_TO;
